import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ErrorBoundaryProvider } from "@/components/ErrorBoundaryProvider";
import React, { Suspense } from "react";
import GlobalLoading from "@/components/GlobalLoading";
import GlobalLoadingOverlay from "@/components/GlobalLoadingOverlay";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ErrorBoundaryProvider>
          <GlobalLoadingOverlay />
          <Suspense fallback={<GlobalLoading message="Loading..." />}>{children}</Suspense>
        </ErrorBoundaryProvider>
      </body>
    </html>
  );
}
